version: "3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker:
    build: .
    command: node worker/worker.js
    environment: 
    - REDIS_HOST=redis 
    - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"